[rospy.client][INFO] 2018-12-05 11:49:54,789: init_node, name[/pose_controller], pid[14489]
[xmlrpc][INFO] 2018-12-05 11:49:54,789: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-05 11:49:54,790: Started XML-RPC server [http://NAOrobUSB001:43569/]
[rospy.init][INFO] 2018-12-05 11:49:54,790: ROS Slave URI: [http://NAOrobUSB001:43569/]
[rospy.impl.masterslave][INFO] 2018-12-05 11:49:54,790: _ready: http://NAOrobUSB001:43569/
[rospy.registration][INFO] 2018-12-05 11:49:54,791: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2018-12-05 11:49:54,791: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2018-12-05 11:49:54,890: registered with master
[rospy.rosout][INFO] 2018-12-05 11:49:54,890: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-05 11:49:54,892: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-05 11:49:54,894: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2018-12-05 11:49:54,914: Connecting to NaoQi at 127.0.0.1:9559
[rospy.internal][INFO] 2018-12-05 11:49:55,012: topic[/joint_trajectory/goal] adding connection to [http://NAOrobUSB001:40893/], count 0
[rospy.internal][INFO] 2018-12-05 11:49:55,014: topic[/joint_trajectory/cancel] adding connection to [http://NAOrobUSB001:40893/], count 0
[rosout][INFO] 2018-12-05 11:49:55,018: nao_controller initialized
[rosout][INFO] 2018-12-05 11:49:55,023: nao pose_controller running...
[rospy.internal][INFO] 2018-12-05 11:49:55,041: topic[/joint_trajectory/feedback] adding connection to [/pose_manager], count 0
[rospy.internal][INFO] 2018-12-05 11:49:55,042: topic[/joint_trajectory/status] adding connection to [/pose_manager], count 0
[rospy.internal][INFO] 2018-12-05 11:49:55,042: topic[/joint_trajectory/result] adding connection to [/pose_manager], count 0
[rospy.internal][INFO] 2018-12-05 11:49:55,121: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-05 11:49:55,635: topic[/joint_stiffness] adding connection to [http://NAOrobUSB001:38817/], count 0
[rosout][ERROR] 2018-12-05 13:45:39,663: Exception caught:
	ALMotion::setStiffnesses
	module destroyed
[rospy.internal][WARNING] 2018-12-05 13:45:39,689: Unknown error initiating TCP/IP socket to NAOrobUSB001:39739 (http://NAOrobUSB001:38817/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2018-12-05 13:45:39,689: topic[/joint_stiffness] removing connection to http://NAOrobUSB001:38817/
[rospy.core][INFO] 2018-12-05 13:45:40,117: signal_shutdown [signal-2]
[rosout][INFO] 2018-12-05 13:45:40,117: Stopping pose_controller
[rospy.internal][ERROR] 2018-12-05 13:45:40,128: Unable to initiate TCP/IP socket to NAOrobUSB001:37539 (http://NAOrobUSB001:40893/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-05 13:45:40,129: Unable to initiate TCP/IP socket to NAOrobUSB001:37539 (http://NAOrobUSB001:40893/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2018-12-05 13:45:40,143: pose_controller stopped
[rospy.internal][INFO] 2018-12-05 13:45:40,151: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-05 13:45:40,151: topic[/joint_trajectory/status] removing connection to /pose_manager
[rospy.internal][INFO] 2018-12-05 13:45:40,151: topic[/joint_trajectory/result] removing connection to /pose_manager
[rospy.internal][INFO] 2018-12-05 13:45:40,151: topic[/joint_trajectory/feedback] removing connection to /pose_manager
[rospy.internal][INFO] 2018-12-05 13:45:40,152: topic[/joint_trajectory/cancel] removing connection to http://NAOrobUSB001:40893/
[rospy.internal][INFO] 2018-12-05 13:45:40,152: topic[/joint_trajectory/goal] removing connection to http://NAOrobUSB001:40893/
[rospy.impl.masterslave][INFO] 2018-12-05 13:45:40,152: signal-2
[rosout][INFO] 2018-12-05 13:45:40,283: nao pose_controller stopped.
[rospy.core][INFO] 2018-12-05 13:45:40,284: signal_shutdown [atexit]
