[rospy.client][INFO] 2018-11-21 11:41:53,147: init_node, name[/rostopic_6330_1542796913124], pid[6330]
[xmlrpc][INFO] 2018-11-21 11:41:53,148: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-11-21 11:41:53,148: Started XML-RPC server [http://NAOrobUSB001:38047/]
[rospy.init][INFO] 2018-11-21 11:41:53,148: ROS Slave URI: [http://NAOrobUSB001:38047/]
[rospy.impl.masterslave][INFO] 2018-11-21 11:41:53,148: _ready: http://NAOrobUSB001:38047/
[rospy.registration][INFO] 2018-11-21 11:41:53,148: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2018-11-21 11:41:53,149: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2018-11-21 11:41:53,248: registered with master
[rospy.rosout][INFO] 2018-11-21 11:41:53,249: initializing /rosout core topic
[rospy.rosout][INFO] 2018-11-21 11:41:53,250: connected to core topic /rosout
[rospy.simtime][INFO] 2018-11-21 11:41:53,251: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2018-11-21 11:41:53,263: topic[/chatter] adding connection to [http://NAOrobUSB001:39399/], count 0
[rospy.internal][INFO] 2018-11-21 11:41:53,547: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2018-11-21 11:42:09,287: Unknown error initiating TCP/IP socket to NAOrobUSB001:37983 (http://NAOrobUSB001:39399/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-11-21 11:42:09,287: topic[/chatter] removing connection to http://NAOrobUSB001:39399/
[rospy.internal][INFO] 2018-11-21 11:42:53,342: topic[/chatter] adding connection to [http://NAOrobUSB001:43561/], count 0
[rospy.core][INFO] 2018-11-21 11:43:12,207: signal_shutdown [signal-2]
[rospy.internal][INFO] 2018-11-21 11:43:12,208: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-11-21 11:43:12,209: topic[/chatter] removing connection to http://NAOrobUSB001:43561/
[rospy.internal][WARNING] 2018-11-21 11:43:12,209: Unknown error initiating TCP/IP socket to NAOrobUSB001:55931 (http://NAOrobUSB001:43561/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2018-11-21 11:43:12,209: signal-2
[rospy.core][INFO] 2018-11-21 11:43:12,310: signal_shutdown [atexit]
