[rospy.client][INFO] 2019-01-17 13:39:32,249: init_node, name[/pepper_robot/pose/pose_controller], pid[17378]
[xmlrpc][INFO] 2019-01-17 13:39:32,249: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-01-17 13:39:32,250: Started XML-RPC server [http://NAOrobUSB001:39591/]
[rospy.init][INFO] 2019-01-17 13:39:32,250: ROS Slave URI: [http://NAOrobUSB001:39591/]
[rospy.impl.masterslave][INFO] 2019-01-17 13:39:32,250: _ready: http://NAOrobUSB001:39591/
[xmlrpc][INFO] 2019-01-17 13:39:32,250: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-01-17 13:39:32,251: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-01-17 13:39:32,350: registered with master
[rospy.rosout][INFO] 2019-01-17 13:39:32,350: initializing /rosout core topic
[rospy.rosout][INFO] 2019-01-17 13:39:32,353: connected to core topic /rosout
[rospy.simtime][INFO] 2019-01-17 13:39:32,355: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-01-17 13:39:32,367: Connecting to NaoQi at 192.168.0.20:9559
[rospy.internal][INFO] 2019-01-17 13:39:33,350: topic[/rosout] adding connection to [/rosout], count 0
[rosout][WARNING] 2019-01-17 13:39:33,356: Collection LLeg not found on your robot.
[rosout][WARNING] 2019-01-17 13:39:33,415: Collection RLeg not found on your robot.
[rospy.internal][INFO] 2019-01-17 13:39:33,613: topic[/pepper_robot/pose/joint_trajectory/feedback] adding connection to [/pepper_robot/pose/pose_manager], count 0
[rospy.internal][INFO] 2019-01-17 13:39:33,614: topic[/pepper_robot/pose/joint_trajectory/result] adding connection to [/pepper_robot/pose/pose_manager], count 0
[rospy.internal][INFO] 2019-01-17 13:39:33,615: topic[/pepper_robot/pose/joint_trajectory/status] adding connection to [/pepper_robot/pose/pose_manager], count 0
[rospy.internal][INFO] 2019-01-17 13:39:33,618: topic[/pepper_robot/pose/joint_trajectory/cancel] adding connection to [http://NAOrobUSB001:33911/], count 0
[rospy.internal][INFO] 2019-01-17 13:39:33,622: topic[/pepper_robot/pose/joint_trajectory/goal] adding connection to [http://NAOrobUSB001:33911/], count 0
[rosout][INFO] 2019-01-17 13:39:33,638: nao_controller initialized
[rosout][INFO] 2019-01-17 13:39:33,639: nao pose_controller running...
[rospy.core][INFO] 2019-01-17 13:39:43,356: signal_shutdown [signal-2]
[rosout][INFO] 2019-01-17 13:39:43,356: Stopping pose_controller
[rosout][INFO] 2019-01-17 13:39:43,356: pose_controller stopped
[rospy.internal][INFO] 2019-01-17 13:39:43,376: topic[/pepper_robot/pose/joint_trajectory/result] removing connection to /pepper_robot/pose/pose_manager
[rospy.internal][INFO] 2019-01-17 13:39:43,376: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-01-17 13:39:43,377: topic[/pepper_robot/pose/joint_trajectory/feedback] removing connection to /pepper_robot/pose/pose_manager
[rospy.internal][INFO] 2019-01-17 13:39:43,377: topic[/pepper_robot/pose/joint_trajectory/status] removing connection to /pepper_robot/pose/pose_manager
[rospy.internal][ERROR] 2019-01-17 13:39:43,377: Unable to initiate TCP/IP socket to NAOrobUSB001:39193 (http://NAOrobUSB001:33911/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2019-01-17 13:39:43,378: topic[/pepper_robot/pose/joint_trajectory/cancel] removing connection to http://NAOrobUSB001:33911/
[rospy.internal][INFO] 2019-01-17 13:39:43,378: topic[/pepper_robot/pose/joint_trajectory/goal] removing connection to http://NAOrobUSB001:33911/
[rospy.impl.masterslave][INFO] 2019-01-17 13:39:43,378: signal-2
[rospy.internal][WARNING] 2019-01-17 13:39:43,774: Unknown error initiating TCP/IP socket to NAOrobUSB001:39193 (http://NAOrobUSB001:33911/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][INFO] 2019-01-17 13:39:43,993: nao pose_controller stopped.
[rospy.core][INFO] 2019-01-17 13:39:43,993: signal_shutdown [atexit]
